# Generated by Django 5.0.7 on 2024-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'Pharmacy', 'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
