# Generated by Django 5.0.7 on 2024-08-09 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_alter_pharmacy_options_pharmacy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_open_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
