# Generated by Django 5.0.7 on 2024-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('appointment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
