# Generated by Django 5.1 on 2024-08-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField(default=0)),
                ('measuring_state', models.CharField(choices=[('Fasting', 'Fasting'), ('Before Meal', 'Before Meal'), ('Before Sleep', 'Before Sleep'), ('Before Exercise', 'Before Exercise'), ('After Exercise', 'After Exercise'), ('After Meal', 'After Meal')], max_length=20)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.IntegerField(default=0)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField(default=0)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Centimeters', 'Centimeters'), ('Inches', 'Inches')], default='Kilograms', max_length=15)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Celcius', 'Celcius'), ('Fahrenheit', 'Fahrenheit')], default='Celcius', max_length=15)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Kilograms', 'Kilograms'), ('Pounds', 'Pounds')], default='Kilograms', max_length=15)),
                ('last_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodpressure')),
                ('blood_sugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodsugar')),
                ('bmi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bmi')),
                ('heart_rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.heartrate')),
                ('height', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.height')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.temperature')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.weight')),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
            },
        ),
    ]
