# Generated by Django 5.0.7 on 2024-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name': 'Vitals', 'verbose_name_plural': 'Vitals'},
        ),
    ]
