# Generated by Django 5.0.7 on 2024-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField()),
                ('signature', models.ImageField(upload_to='')),
                ('registration_number', models.IntegerField()),
                ('registration_council', models.CharField(max_length=50)),
                ('registration_year', models.DateField()),
                ('rating', models.IntegerField(choices=[(1, 'ONE_STAR'), (2, 'TWO_STAR'), (3, 'THREE_STAR'), (4, 'FOUR_STAR'), (5, 'FIVE_STAR')])),
                ('specialty', models.CharField(choices=[('ALLERGY_AND_IMMUNOLOGY', 'Allergy and Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('FAMILY_MEDICINE', 'Family Medicine'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('MEDICAL_GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR_MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS_AND_GYNAECOLOGY', 'Obstetrics and Gynaecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PAEDIATRICS', 'Paediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], max_length=100)),
                ('consultation_fee', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_description', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('note_status', models.CharField(choices=[('Issued', 'Issued'), ('Revoked', 'Revoked')], default='Issued', max_length=20)),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('doctor_signature', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': "Doctor's Note",
                'verbose_name_plural': "Doctor's Notes",
                'ordering': ['-date_of_issue'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(choices=[('21st Century fish oil', '21st Century fish oil'), ('Abidec', 'Abidec'), ('Accord Bendroflumethiazide', 'Accord Bendroflumethiazide'), ('ACCULOL', 'ACCULOL'), ('Actavis Doxycycline', 'Actavis Doxycycline'), ('Actinaza', 'Actinaza'), ('Aday kit tablets', 'Aday kit tablets'), ('Afrab vite', 'Afrab vite'), ('Africolo 1000 Capsules', 'Africolo 1000 Capsules')], max_length=50)),
                ('medication_form', models.CharField(choices=[('Tablet', 'TABLET'), ('Capsule', 'CAPSULE'), ('Liquid', 'LIQUID'), ('Topical', 'TOPICAL'), ('Drops', 'DROPS'), ('Foam', 'FOAM'), ('Spray', 'SPRAY'), ('Powder', 'POWDER'), ('Injection', 'INJECTION'), ('Patch', 'PATCH'), ('Cream', 'CREAM'), ('Lotion', 'LOTION')], max_length=50)),
                ('dosage', models.IntegerField(default=0)),
                ('no_times', models.IntegerField(default=1)),
                ('frequency', models.CharField(choices=[('Daily', 'DAILY'), ('Weekly', 'WEEKLY'), ('Monthly', 'MONTHLY'), ('Twice a week', 'TWICE_A_WEEK'), ('Alternative days', 'ALTERNATIVE_DAYS'), ('Every fortnight', 'FORTNIGHT')], max_length=50)),
                ('meal_instruction', models.CharField(choices=[('Before meal', 'BEFORE_MEAL'), ('With meal', 'WITH_MEAL'), ('In between meal', 'INBETWEEN_MEAL'), ('After meal', 'AFTER_MEAL'), ('Empty stomach', 'EMPTY_STOMACH'), ('Before sleep', 'BEFORE_SLEEP')], max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_unit_of_weight', models.CharField(choices=[('mg', 'MILLIGRAMS'), ('mcg', 'MICROGRAMS'), ('mcg', 'MICROGRAMS'), ('ng', 'NANOGRAMS'), ('pg', 'PICOGRAMS'), ('pg', 'PICOGRAMS'), ('ml', 'MILLILITRES'), ('microlitres', 'MICROLITRES')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_firstname', models.CharField(max_length=100)),
                ('patient_lastname', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(default=0)),
                ('patient_sex', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=10)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('dosage', models.IntegerField()),
                ('no_times', models.IntegerField(default=1)),
                ('frequency', models.CharField(choices=[('Daily', 'DAILY'), ('Weekly', 'WEEKLY'), ('Monthly', 'MONTHLY'), ('Twice a week', 'TWICE_A_WEEK'), ('Alternative days', 'ALTERNATIVE_DAYS'), ('Every fortnight', 'FORTNIGHT')], max_length=50)),
                ('meal_instruction', models.CharField(choices=[('Before meal', 'BEFORE_MEAL'), ('With meal', 'WITH_MEAL'), ('In between meal', 'INBETWEEN_MEAL'), ('After meal', 'AFTER_MEAL'), ('Empty stomach', 'EMPTY_STOMACH'), ('Before sleep', 'BEFORE_SLEEP')], max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
